### ISSUE TITLE
Pick a License, Any License

### ISSUE THREAD

**Issue by jhabdas** [pantheon-systems/terminus-installer#29]
https://blog.codinghorror.com/pick-a-license-any-license/

**Comment by jhabdas** [comment]
https://github.com/pantheon-systems/terminus-installer/blob/master/composer.json#L6 shows MIT while no license has been given to this repository. If the intent is to open source this work under the MIT license please provide a `LICENSE` or `COPYING` file in the root of the repository to make this software more useful to the community.

Thanks for being open source.

**Comment by davidstrauss** [comment]
Added in #37.
