### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' in reflection-docblock/src/DocBlock/StandardTagFactory.php

### ISSUE THREAD

**Issue by anderm3** [pantheon-systems/terminus-installer#30]
Sometime after 11:20am Eastern on July 15th something changed which is causing the terminus to no longer work for me. What makes this even more confusing is the fact that this codebase has not changed since March 10th and my usage of the code is built into a single purpose docker image and that hasn't been updated since March 6th.

1. The name and version of your OS
A docker image based on `python:2.7-slim`

2. The name and version of your terminal client
Bash 4.3.30

3. Which version of PHP you are using - _you must be running 5.5.9 or later_
PHP 5.6.30-0+deb8u1

4. All relevant Terminal text, including the command and its output(s)

```
root@3ac6c5c11c69:/usr/src/bin-database-backups# terminus auth:login --machine-token=$PANTHEON_AUTOMATION_MACHINE_TOKEN
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The tag "@usage: terminus env:view <site>.<env>
   Opens the browser to <site>'s <env> environment." does not seem to be wellformed, please check it for errors' in /usr/src/bin-database-backups/bin/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php:165
Stack trace:
#0 /usr/src/bin-database-backups/bin/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(114): phpDocumentor\Reflection\DocBlock\StandardTagFactory->extractTagParts('@usage: terminu...')
#1 /usr/src/bin-database-backups/bin/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(231): phpDocumentor\Reflection\DocBlock\StandardTagFactory->create('@usage: terminu...', Object(phpDocumentor\Reflection\Types\Context))
#2 /usr/src/bin-database-backups/bin/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(96): phpDocumentor\Reflection\DocBlockFactory->parseTagBlock('\n\n@authorize\n\n@...', Object(phpDocumentor\Reflection\ in /usr/src/bin-database-backups/bin/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php on line 165
```

terminus is installed as one of the first things this docker image does with the following command;
`curl -sO https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar --quiet install
`

**Comment by theboyk** [comment]
Getting the exact same error on a new installation today.

The name and version of your OS
OS X 10.12

The name and version of your terminal client
Bash 3.2.57(1)-release

Which version of PHP you are using - you must be running 5.5.9 or later
5.6.30

**Comment by anderm3** [comment]
This has cleared up for me. My assumption is that one of the PHP packages required by terminus-installer had a bug in a released version and they have fixed that issue.
